# Generated by Django 2.1.5 on 2020-08-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activityperiods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=30)),
                ('startime', models.CharField(max_length=30)),
                ('endtime', models.CharField(max_length=30)),
            ],
        ),
    ]
